### ISSUE TITLE
Suggestion: Add option to only allow a button to be clicked once

### ISSUE THREAD

**Issue by sbrl** [kylepaulsen/NanoModal#1]
It would be helpful if I could specify that a user should only be allowed to click a button once. After that, the button should be disabled.

**Comment by kylepaulsen** [comment]
You made me realize that this library doesn't make it easy to get at the button that you clicked on. I fixed that.

See here to do what you want:
http://jsfiddle.net/2prosxa8/

**Comment by sbrl** [comment]
It took me a minute to figure out what you had done (I am new to this), but that is so clever!

That is a very neat solution - Thank you :)

**Comment by kylepaulsen** [comment]
No problem!
