### ISSUE TITLE
On long pages, the dialog box appears at the top of the page

### ISSUE THREAD

**Issue by sbrl** [kylepaulsen/NanoModal#2]
**Reproduction steps:**
1. Create a long page
2. Put a button at the bottom that opens a nanoModal
3. Scroll down and click the button

**What should happen:** The nanoModal appears in the centre of the screen

**What actually happens:** The nanoModal appears in the centre of the scrren if the user has scrolled to the top.

Demonstration: https://rawgit.com/sbrl/47e46dae9de255a53a52/raw/90b584e77b656fce474e625929fe94e32ed96ac6/nanoModal-position-text.html

Gist: https://gist.github.com/sbrl/47e46dae9de255a53a52

**Comment by kylepaulsen** [comment]
So this is kind of a tricky problem... when I was building NanoModal, I didn't want to take too much control of where the modal shows up so people could customize where and how it shows up. Also, having a modal show near the top of the screen makes things easy for mobile.

However, I can still help you out:

```
.nanoModal.nanoModalOverride {
    position: fixed;
}
```

This CSS will make it appear near the top of your screen no matter how scrolled down you are. Keep in mind though, that position: fixed might do weird things on mobile - might want to test that out.

This Issue got me thinking that it might be a common want to have the modal show up directly in the center of your screen... So I might add a function to help with that. Let me know if the css helped or of any other thoughts you have.

**Comment by sbrl** [comment]
Thanks!

That CSS fixes it, thank you :)

Demo: https://rawgit.com/sbrl/47e46dae9de255a53a52/raw/e0a1cf75b8e082e046d3d5aa8754e587b8c2895c/nanoModal-position-text.html

Gist: https://gist.github.com/sbrl/47e46dae9de255a53a52

I need it for a cloud based [bookmark storage solution](https://github.com/sbrl/bloworm) that I am building, where the page can get very long indeed.

**Comment by kylepaulsen** [comment]
Glad to help!
