### ISSUE TITLE
Show in the center of a parent element

### ISSUE THREAD

**Issue by mitchlabrador** [kylepaulsen/NanoModal#3]
Hello,

I'm trying to use NanoModal to show the modal and overlay inside a particular parent element other than the body.

For example, imagine you have a page that has two divs side by side each taking 50% of the page. I want NanoModal to come up for the content working on the right div (in the center of the right div), and the overlay with the opacity to be over the right div only as well. In other words the modal is for the content inside the right div, so the left div content should not be overlayed.

Is this possible?

Great script BTW, thanks for sharing!

Regards,
Mitch

**Comment by kylepaulsen** [comment]
Hey!

So it sounds like you have a fairly specific use case. Most modals are supposed to cover the entire page. The way I built this library would make it very hard to add that functionality in. However! I can still help you. Check out this JS Fiddle:

http://jsfiddle.net/bvkf07oj/

Basically you can create your own overlay for each side pretty easily. Then you just use the modal api's onShow and onHide methods to show and hide your overlays respectively. Also appending the modal to the left or right div will help you get it positioned on the right side. You can see all the details in the fiddle. Good Luck!

**Comment by mitchlabrador** [comment]
Thanks Kyle!

Works great.

Mitch

**Comment by kylepaulsen** [comment]
No problem. :)
